name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake.svg from commits
        uses: Platane/snk@v3
        with:
          github_user_name: Sacchi4649
          outputs: dist/github-contribution-grid-snake.svg
          snake_color: "#FF003C"
          background: "transparent"

      - name: Push generated snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
